### ISSUE TITLE
Insufficient VRAM for model and cache

### ISSUE THREAD

**Issue by dagbdagb** [turboderp/exui#11]
A bit out of my depth here, but at least exui now loads without error.

Tried loading this model:
https://huggingface.co/TheBloke/Llama-2-7B-32K-Instruct-GPTQ

exui insists "RuntimeError: Insufficient VRAM for model and cache"

I have 8GB, I believe this should be sufficient for this model? Care to hint at where I am missing the boat?

**Comment by turboderp** [comment]
That particular model loads with a default context length of 32768 tokens, which is a bit too much for 8 GB, I think even in FP8 cache mode. You can try reducing the max sequence length.

**Comment by dagbdagb** [comment]
tried another model, which loads. Looks like you are right. :-)

**Comment by turboderp** [comment]
You can probably load the 32k model as well if you just set a lower context length.
