### ISSUE TITLE
How to increase max_tokens to 4096

### ISSUE THREAD

**Issue by xldistance** [turboderp/exui#23]
I set maxtokens to 4096 in get_default_notepad_settings, and the ui still displays 2048 as the max value.
![QQ截图20231216132208](https://github.com/turboderp/exui/assets/29418474/bf540636-8153-44a6-8dff-fd918ca970cc)

**Comment by xldistance** [comment]
I changed the location of the file.

**Comment by aliencaocao** [comment]
how did you change?
