### ISSUE TITLE
Error "architectures"

### ISSUE THREAD

**Issue by Gyramuur** [turboderp/exui#29]
Trying to set up and use ExUI, I went through the entire install process detailed here: https://github.com/turboderp/exui/blob/master/doc/manual-install.md

I used CUDA 12.1, installed the recommended wheel, following the instructions which said: 

"For example if you have Windows 11 or Windows 10 running on a 64-bit CPU (most common), are using CUDA 12.1, and Python 3.10, download exllamav2-0.0.9+cu121-cp310-cp310-win_amd64.whl"

As all of the above about Windows 10, Cuda version, and Python 3.10 were all correct, I downloaded the recommended wheel.

Was able to launch server.py, but when I try to add a model folder, it complained that config.json was missing. I went and got it from the model page, here: https://huggingface.co/TheBloke/MLewd-ReMM-L2-Chat-20B-GGUF/tree/main?not-for-all-audiences=true

After providing that, it still doesn't load the model and sits there with a cryptic error message. All it says is "architectures":

![image](https://github.com/turboderp/exui/assets/7817917/197e0324-dee1-462c-8784-77dc23908e1c)

DxDiag: https://pastebin.com/wHrPkQs5

**Comment by turboderp** [comment]
It won't load GGUF models. You need either GPTQ, EXL2 or FP16 models. TheBloke likely has a GPTQ version of that model on HF, though.

**Comment by Gyramuur** [comment]
> It won't load GGUF models. You need either GPTQ, EXL2 or FP16 models. TheBloke likely has a GPTQ version of that model on HF, though.

It worked, thanks :D
