### ISSUE TITLE
"copy text" button in code ouput windows?

### ISSUE THREAD

**Issue by dagbdagb** [turboderp/exui#36]
Is it a lot of work to add a "copy text" button in the top right corner whenever the LLM dumps code or whatever in a 'window'?
Like here:
![image](https://github.com/turboderp/exui/assets/8895912/e60e599a-db22-4ea2-86ef-e7bbcfdcb95e)

**Comment by turboderp** [comment]
Yes, that's pretty easy. Try the latest commit.

**Comment by dagbdagb** [comment]
That was entirely too easy. I should have asked a month ago.   :-)
Thank you! And thank you for exllama/exui.

**Comment by dagbdagb** [comment]
completed as requested
