### ISSUE TITLE
Answer does not escape HTML tags

### ISSUE THREAD

**Issue by chaincrafter** [turboderp/exui#41]
Hello,
the newest version does not escape HTML tags in answers. So it does not show the code, instead it renders the output as HTML. See example image below.

![image](https://github.com/turboderp/exui/assets/46602837/af172d3c-d85d-4b3b-82cd-06c32115dceb)

**Comment by turboderp** [comment]
It was a side effect of adding the copy  button. Should be fixed now.

**Comment by chaincrafter** [comment]
Fixed.
