### ISSUE TITLE
Edit context

### ISSUE THREAD

**Issue by dagbdagb** [turboderp/exui#43]
When iterating over something, it is occasionally useful to go back in time. In effect, removing from context anything that happened after a certain point. 

My first instinct was to allow for setting 'bookmarks'. But this is a bit rigid. Is it feasible to create a client side feature which effectively says "delete from here to the end"?

**Comment by turboderp** [comment]
I will look into adding some more usability features like that in a bit. Currently you'd have to delete the blocks one by one which I guess is a little inconvenient.

**Comment by turboderp** [comment]
Should be added now.

**Comment by dagbdagb** [comment]
LGTM.
