### ISSUE TITLE
how to name the sessions?

### ISSUE THREAD

**Issue by Fuckingnameless** [turboderp/exui#45]

**Comment by turboderp** [comment]
You should be able to just doubleclick on the conversation title in the list.

**Comment by Fuckingnameless** [comment]
> You should be able to just doubleclick on the conversation title in the list.

damn i'm an idiot

**Comment by Fuckingnameless** [comment]
> You should be able to just doubleclick on the conversation title in the list.

is there a way to add custom prompt format?

**Comment by turboderp** [comment]
Not at the moment, no. There's a couple of builtin formats, and I might add Jinja support (for loading prompt formats from tokenizer_config.json, although it's a little cumbersome to work with. For now, if you're up for a little coding it's pretty straightforward to add more formats to backend/prompts.py.
