### ISSUE TITLE
Cant point to the model dir

### ISSUE THREAD

**Issue by RecoveredApparatus** [turboderp/exui#8]
![image](https://github.com/turboderp/exui/assets/137035432/d5b8f9ee-5714-4ef7-80e8-3d835a5824ca)

Method:Wget
Model:Llama-2-7b-exl2

Note:I m not really sure if i should point to the safetensors or the config file

**Comment by turboderp** [comment]
You'll want to point to the directory containing all of the model's files, including the .safetensors file(s), config.json and tokenizer.model.

**Comment by RecoveredApparatus** [comment]
is that case i l need to git clone instead of wget

**Comment by turboderp** [comment]
You can `wget` the individual files, but `git clone` is easier, as long as you have git-lfs set up so you're actually downloading the files.

Another option is to use `huggingface-cli` or the `huggingface_hub` package. [Some instructions here.](https://huggingface.co/docs/huggingface_hub/guides/download)
